name: dart_mistral_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/malengatiger/dart_mistral_api

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  json_annotation: ^4.8.1
  pretty_print_json: ^1.0.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.8
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  license_generator: ^2.0.0
